name: Auto Update Cache Version

on:
  push:
    branches:
      - main

jobs:
  update-sw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject timestamp ke sw.js
        run: |
          TIMESTAMP=$(date +%s)
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_ENV"
          sed -i -E "s/(saku-santri-)[0-9]+/\1$TIMESTAMP/" santri/sw.js
          sed -i -E "s/(bendahara-)[0-9]+/\1$TIMESTAMP/" bendahara/sw.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add santri/sw.js bendahara/sw.js
          git commit -m "Auto: update cache $TIMESTAMP" || echo "No changes"
          git push
